### ISSUE TITLE
Strange behavior in Acrobat Reader DC

### ISSUE THREAD

**Issue by koppor** [zauguin/intopdf#3]
Acrobat Reader does not show the filename of the attachment any more (it uses two strange characters as file name) - and it does not allow to open the attachment any more:

![grafik](https://user-images.githubusercontent.com/1366654/178369821-f8b0cf9b-0e0e-43ea-946e-51fcc629dc94.png)

Maybe, if the filename is "fixed", the attachment can be opened again?

**Comment by zauguin** [comment]
Does this happen only for newly created documents or also for older documents opened with newer versions of Acrobat Reader?

**Comment by koppor** [comment]
I opened `intopdf.pdf` from 2021-02-26 (older document). I also opened a newly created file. Both show this behavior in newer version of Acrobat Reader. 

SumatraPDF cannot open the attached file either (not sure if it could back in 2018.)

**Comment by koppor** [comment]
I tried to find out the SumatraPDF version, where it worked:

| Version | working |
| -- | -- |
| 2.5.2 | yes |
| 3.0 | yes |
| 3.1.2 (2016-08-14) | yes |
| 3.2 (2020-03-15) | no |
| 3.3.3 | no |

The change history: https://www.sumatrapdfreader.org/docs/Version-history.

It seems that `mupdf` got updated. The changes are listed there: https://github.com/sumatrapdfreader/sumatrapdf/commits/3.2/mupdf. Maybe, it comes from https://github.com/sumatrapdfreader/sumatrapdf/commit/0bf8fcf89d1d3b5a2df85d3ca04af82af1a4a34d.

I tried mupdf itself, but it cannot open attachments at all (checked until 1.19) - even though the changelog indicates differently: https://github.com/ArtifexSoftware/mupdf/blob/961859501bf226e9ae335b03c9d64eee9a556f7b/CHANGES#L113

Do I need to open an issue at SumatraPDF?

I could not check AcrobatReader until now. Even with Chocolatey, it does not install the "right" version. I think, I tried 2019.010.20064, which did not work.

**Comment by koppor** [comment]
I tried some other PDF viewers:

- Okular 22.04.2 works
- Foxit Reader 12.0.0.12394: Does not work
- Foxit Reader 9.7.2.29539 (May 2, 2020): works, but shows `þÿ` as filename
- Foxit Reader 8.3.2.25013 (September 1, 2017): doe snot show anything

**Comment by zauguin** [comment]
Does the file under https://math.hamburg/s/xQWpANnd7gKT97r work better?

**Comment by koppor** [comment]
- Acrobat Reader: works
- Adobe Acrobat XI [11.0.23.22](http://11.0.23.22/): works
- Foxit Reader 12.0.0.12394: attachment correctly shown; link does NOT work
- Foxit Reader 9.7.2.29539: works - and shows correct file name (in
contrast to other PDF)
- SumatraPDF 3.4.6: nope
. SumatraPDF 3.1.2: works (and shows correct file name)

I think, this is good to go - and I'll file an issue against SumatraPDF (maybe it's related to https://github.com/sumatrapdfreader/sumatrapdf/issues/1738).

**Comment by zauguin** [comment]
It seems a bit suspicous that two readers support this worse in later versions, but I released a version with the current fix for the time being.

**Comment by koppor** [comment]
Thank you! I totally overlooked the branch https://github.com/zauguin/intopdf/tree/l3drivers 😇

**Comment by zauguin** [comment]
Sorry, I kind of assumed that I had changed the default branch when switching to the l3 code, but I actually just merged it. I now moved the branches around and it is back to one branch containing everything.
